name: ai-api

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: trigger info
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: balck checks
        run: python3 -m black . -l 120 --check --verbose --diff --color
      - name: testing
        run: python3 -m pytest . -s
      - name: complete info
        run: echo "All checks passed successfully! ✅"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: complete info
        run: echo "Deployment was successful! ✅"
